"""empty message

Revision ID: 727463f38909
Revises: 988f59d189d8
Create Date: 2025-02-03 10:38:37.510781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '727463f38909'
down_revision = '988f59d189d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('full_name', sa.String(length=80), nullable=False))
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('full_name')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
